import { UserProfile, LeaveRequest, AppSettings } from '../types';

export const INITIAL_DEMO_USERS: UserProfile[] = [
  {
    id: 'user_admin',
    email: 'admin@office.internal',
    username: 'admin',
    displayName: 'Office HR Administrator',
    role: 'admin',
    jobTitle: 'HR Operations Lead',
    department: 'Human Resources',
    phoneNumber: '+977-9801234567',
    leaveBalance: {
      annual: 18,
      sick: 12,
      casual: 6,
      emergency: 5,
      unpaidTaken: 0,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user_coord',
    email: 'coordinator@office.internal',
    username: 'coordinator',
    displayName: 'Pooja Shrestha (Coordinator)',
    role: 'coordinator',
    jobTitle: 'Operations & Leave Coordinator',
    department: 'Administration',
    phoneNumber: '+977-9841234568',
    leaveBalance: {
      annual: 18,
      sick: 12,
      casual: 6,
      emergency: 5,
      unpaidTaken: 0,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user_dcd',
    email: 'dcd@office.internal',
    username: 'dcd',
    displayName: 'Rajesh Sharma (Deputy Country Director)',
    role: 'dcd',
    jobTitle: 'Deputy Country Director',
    department: 'Executive Leadership',
    phoneNumber: '+977-9811234569',
    leaveBalance: {
      annual: 24,
      sick: 15,
      casual: 8,
      emergency: 5,
      unpaidTaken: 0,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user_cd',
    email: 'cd@office.internal',
    username: 'cd',
    displayName: 'Dr. Evelyn Vance (Country Director)',
    role: 'cd',
    jobTitle: 'Country Director',
    department: 'Executive Leadership',
    phoneNumber: '+977-9851234570',
    leaveBalance: {
      annual: 25,
      sick: 15,
      casual: 10,
      emergency: 5,
      unpaidTaken: 0,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user_emp1',
    email: 'aarav.kc@office.internal',
    username: 'aarav',
    displayName: 'Aarav K.C.',
    role: 'employee',
    jobTitle: 'Senior Program Officer',
    department: 'Programs & Development',
    phoneNumber: '+977-9861234571',
    leaveBalance: {
      annual: 14,
      sick: 10,
      casual: 4,
      emergency: 5,
      unpaidTaken: 0,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user_emp2',
    email: 'sunita.lama@office.internal',
    username: 'sunita',
    displayName: 'Sunita Lama',
    role: 'employee',
    jobTitle: 'M&E Specialist',
    department: 'Monitoring & Evaluation',
    phoneNumber: '+977-9871234572',
    leaveBalance: {
      annual: 16,
      sick: 8,
      casual: 5,
      emergency: 5,
      unpaidTaken: 0,
    },
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_APP_SETTINGS: AppSettings = {
  defaultWorkflowMode: 'digital',
  allowPaperbackMode: true,
  organizationName: 'Country Office Program Mission',
  countryOffice: 'Nepal Country Office',
  linkedGoogleDriveFolderName: 'Office_Leave_Management_Archive',
  linkedGoogleSheetName: 'Country_Office_Leave_Master_Records_2026',
  googleCalendarId: 'primary',
  autoDeductBalance: true,
  autoSyncCalendar: true,
  autoSyncSheets: true,
};

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lr_001',
    trackingNumber: 'LR-2026-0001',
    employeeId: 'user_emp1',
    employeeName: 'Aarav K.C.',
    employeeEmail: 'aarav.kc@office.internal',
    employeeDepartment: 'Programs & Development',
    employeeJobTitle: 'Senior Program Officer',
    leaveType: 'Annual Leave',
    startDate: '2026-09-05',
    endDate: '2026-09-08',
    totalDays: 4,
    reason: 'Family cultural celebration and annual festival travel to hometown.',
    contactDuringLeave: '+977-9861234571',
    handoverPerson: 'Sunita Lama',
    handoverNotes: 'Project quarterly reporting slides completed and shared on Google Drive.',
    workflowMode: 'digital',
    status: 'pending_coordinator',
    attachments: [],
    employeeSignature: {
      signedAt: '2026-08-28T09:30:00Z',
      signeeName: 'Aarav K.C.',
    },
    history: [
      {
        timestamp: '2026-08-28T09:30:00Z',
        actorId: 'user_emp1',
        actorName: 'Aarav K.C.',
        actorRole: 'employee',
        action: 'submit',
        notes: 'Submitted digital leave request for 4 days Annual Leave',
      },
    ],
    createdAt: '2026-08-28T09:30:00Z',
    updatedAt: '2026-08-28T09:30:00Z',
  },
  {
    id: 'lr_002',
    trackingNumber: 'LR-2026-0002',
    employeeId: 'user_emp2',
    employeeName: 'Sunita Lama',
    employeeEmail: 'sunita.lama@office.internal',
    employeeDepartment: 'Monitoring & Evaluation',
    employeeJobTitle: 'M&E Specialist',
    leaveType: 'Sick Leave',
    startDate: '2026-09-01',
    endDate: '2026-09-02',
    totalDays: 2,
    reason: 'Medical examination and follow-up clinical therapy.',
    contactDuringLeave: '+977-9871234572',
    handoverPerson: 'Aarav K.C.',
    handoverNotes: 'Daily field monitoring logs assigned to Aarav.',
    workflowMode: 'paperback',
    status: 'pending_coordinator',
    attachments: [],
    employeeSignature: {
      signedAt: '2026-08-29T11:15:00Z',
      signeeName: 'Sunita Lama',
    },
    history: [
      {
        timestamp: '2026-08-29T11:15:00Z',
        actorId: 'user_emp2',
        actorName: 'Sunita Lama',
        actorRole: 'employee',
        action: 'submit',
        notes: 'Paperback application submitted. Printed form signed by employee.',
      },
    ],
    createdAt: '2026-08-29T11:15:00Z',
    updatedAt: '2026-08-29T11:15:00Z',
  },
  {
    id: 'lr_003',
    trackingNumber: 'LR-2026-0003',
    employeeId: 'user_emp1',
    employeeName: 'Aarav K.C.',
    employeeEmail: 'aarav.kc@office.internal',
    employeeDepartment: 'Programs & Development',
    employeeJobTitle: 'Senior Program Officer',
    leaveType: 'Casual Leave',
    startDate: '2026-08-10',
    endDate: '2026-08-11',
    totalDays: 2,
    reason: 'Personal urgent banking and administrative documentation.',
    workflowMode: 'digital',
    status: 'approved',
    attachments: [],
    employeeSignature: {
      signedAt: '2026-08-01T08:00:00Z',
      signeeName: 'Aarav K.C.',
    },
    coordinatorVerification: {
      verifiedAt: '2026-08-01T10:00:00Z',
      coordinatorId: 'user_coord',
      coordinatorName: 'Pooja Shrestha',
      notes: 'Balance checked. 4 casual days were remaining.',
    },
    dcdApproval: {
      approvedAt: '2026-08-02T14:30:00Z',
      dcdId: 'user_dcd',
      dcdName: 'Rajesh Sharma',
      comments: 'Recommended. Work handover in place.',
      signatureUrl: 'e-sign-dcd-verified',
    },
    cdApproval: {
      approvedAt: '2026-08-03T16:00:00Z',
      cdId: 'user_cd',
      cdName: 'Dr. Evelyn Vance',
      comments: 'Approved. Enjoy your leave.',
      signatureUrl: 'e-sign-cd-verified',
    },
    googleCalendarEventId: 'cal_aug_001_aarav',
    googleSheetRowLogged: true,
    history: [
      {
        timestamp: '2026-08-01T08:00:00Z',
        actorId: 'user_emp1',
        actorName: 'Aarav K.C.',
        actorRole: 'employee',
        action: 'submit',
      },
      {
        timestamp: '2026-08-01T10:00:00Z',
        actorId: 'user_coord',
        actorName: 'Pooja Shrestha',
        actorRole: 'coordinator',
        action: 'verify',
        notes: 'Verified and forwarded to DCD',
      },
      {
        timestamp: '2026-08-02T14:30:00Z',
        actorId: 'user_dcd',
        actorName: 'Rajesh Sharma',
        actorRole: 'dcd',
        action: 'dcd_approve',
        notes: 'DCD e-signed and forwarded to CD',
      },
      {
        timestamp: '2026-08-03T16:00:00Z',
        actorId: 'user_cd',
        actorName: 'Dr. Evelyn Vance',
        actorRole: 'cd',
        action: 'cd_approve',
        notes: 'Final CD approval granted. Google Calendar synced and Sheet logged.',
      },
    ],
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-03T16:00:00Z',
  }
];
